Facial Recognition: /mnt/c/ABC/CS/github/Facial-Recognition/src/libs/linalg.c File Reference
linalg.c File Reference
File containing common linear algebra functions.
#include "linalg.h"
Functions
vector * vector_create (size_t size)
matrix * matrix_create (size_t row, size_t col)
matrix * vec_to_mat (vector *vec, int orientation)
Converts vector into matrix this function will "cast" the vector into a matrix by using the fact that they both have the same size. when calling this function, calling free() on the matrix will free the vector and vice versa.
void matrix_reshape (matrix *mat, size_t row, size_t col)
Reshapes the matrix this function will reshape the matrix in constant time.
double dot_product (const double *x, const double *y, int length)
Performs dot product on two arrays this function will malloc for the user a double arrays must be of same size.
vector * vecmat_multiply (const vector *vec, const matrix *mat)
Performs vector * matrix this function will malloc for the user a vector*.
vector * matvec_multiply (const matrix *mat, const vector *vec)
Performs matrix * vector this function will malloc for the user a vector*.
void mat_print (const matrix *mat)
prints the matrix this function will not modify the matrix and print to stdout
void vec_print (const vector *vec)
prints the vector this function will not modify the vector and print to stdout
matrix * matmat_multiply (const matrix *matA, const matrix *matB)
Performs matrixA * matrixB this function will malloc for the user a matrix*.
matrix * matmat_addition (const matrix *matA, const matrix *matB)
Performs matrixA + matrixB this function will malloc for the user a matrix*.
matrix * matmat_subtraction (const matrix *matA, const matrix *matB)
Performs matrixA - matrixB this function will malloc for the user a matrix*.
matrix * matscalar_multiply (const matrix *matA, const double scalar)
Performs matrixA * scaler this function will malloc for the user a matrix*.
matrix * matscalar_divide (const matrix *matA, const double scalar)
Performs matrixA / scaler this function will malloc for the user a matrix*.
matrix * mat_transpose (const matrix *mat)
Performs transpose(mat) this function will malloc for the user a matrix*.
void vec_append (vector **vec_a, vector *vec_b)
Performs vec = vec_a+vec_b this function will realloc vec_a and free vec_b.
void eigen (int n, double a[], int it_max, double v[], double d[], int *it_num, int *rot_num)
Performs Jacobi eigenvalue iteration this function will.
void mat_identity (int n, double a[])
returns an identity matrix of size n
void diag_vector (int n, double a[], double v[])
gets the diagonal entries
double frobenius_norm (int n, int k, double a[], double x[], double lambda[])
computes the Frobenius norm in a right eigensystem
matrix * covmat (matrix *mat)
computes the variance covariance matrix this function will malloc a new matrix
Detailed Description
File containing common linear algebra functions.
Minhyuk Park
Date
7 Nov 2017
Function Documentation
matrix* covmat (matrix * mat)
computes the variance covariance matrix this function will malloc a new matrix
Parameters
matrix* mat the input matrix of deviation scores of size n by k
Returns
matrix* the output variance-covariance matrix
References mat_transpose(), matmat_multiply(), and matscalar_divide().
{
     size_t n = mat->row;
     matrix* mat_T = mat_transpose(mat);
     matrix* x_T_x = matmat_multiply(mat_T, mat);
     matrix* retmat = matscalar_divide(x_T_x, n);
     free(x_T_x);
     free(mat_T);
     return retmat;
 }
void diag_vector (int n, double a[], double v[])
gets the diagonal entries
Parameters
n the dimension
a[] input the matrix, N by N
v[] output the diagonal entries, N
Referenced by eigen().
{
     for(int i = 0; i < n; i ++) {
         v[i] = a[i + i * n];
     }
     return;
 }
double dot_product (const double * x, const double * y, int length)
Performs dot product on two arrays this function will malloc for the user a double arrays must be of same size.
Returns
a double
Parameters
first array
second array
length of arrays
Referenced by matvec_multiply().
 {
     double retVal = 0.0;
     for(int i =0;i<length; i++)
     {
         retVal+=(x[i] *y[i]);
     }
     return retVal;
 }
void eigen (int n, double a[], int it_max, double v[], double d[], int * it_num, int * rot_num)
Performs Jacobi eigenvalue iteration this function will.
Parameters
N the dimiension of the input matrix a, which is a N by N matrix
a[] the input matrix which has to be square, real, and symmetric
it_max maximum number of iterations to stop at
v[] output matrix of eigenvectors, which is a N by N matrix
d[] output matrix of eigenvalues, in descending order
it_num output total number of iterations
rot_num output total number of rotations
References diag_vector(), and mat_identity().
{
     mat_identity(n, v); // create the identity matrix using what the caller allocated for us
     diag_vector(n, a, d); // get the diagonal values of a and store it in caller allocated vector d
     double* bw = (double*) malloc(n * sizeof(double));
     double* zw = (double*) malloc(n * sizeof(double));
     for(int i = 0; i < n; i ++) {
         bw[i] = d[i];
         zw[i] = 0.0;
     }
     *it_num = 0;
     *rot_num = 0;
     double thresh = 0.0;
     double gapq = 0.0;
     while(*it_num < it_max) {
         *it_num += 1;
         thresh = 0.0;
         // set up the convergence threshold
         // based on the size of strict upper triangle
         for(int i = 0; i < n; i ++) {
             for(int j = 0; j < i; j ++) {
                 thresh += (a[j + i * n] * a[j + i * n]);
             }
         }
         // PASS 1
         thresh = sqrt(thresh) / (double)(4 * n);
         if(thresh == 0.0) {
             break;
         }
         // PASS 2
         for(int p = 0; p < n; p ++) {
             for(int q = p + 1; q < n; q ++) {
                 gapq = 10.0 * fabs(a[p + q * n]);
                 double termp = gapq + fabs(d[p]);
                 double termq = gapq + fabs(d[q]);
                 if(4 < *it_num && termp == fabs(d[p]) && termq == fabs(d[q])) {
                     a[p + q * n] = 0.0;
                 // apply rotation otherwise
                 // PASS 3
                 } else if(thresh <= fabs(a[p + q * n])) {
                     double h = d[q] - d[p];
                     double term = fabs(h) + gapq;
                     double t = 0.0;
                     if(term == fabs(h)) {
                         t = a[p + q * n] / h;
                     } else {
                         double theta = 0.5 * h / a[p + q * n];
                         t = 1.0 / (fabs(theta) + sqrt(1.0 + theta * theta));
                         if(theta < 0.0) {
                             t = -t;
                         }
                     }
                     // PASS 4
                     double c = 1.0 / sqrt(1.0 + t * t);
                     double s = t * c;
                     double tau = s / (1.0 + c);
                     h = t * a[p + q * n];
                     zw[p] -= h;
                     zw[q] += h;
                     d[p] -= h;
                     d[q] += h;
                     a[p + q * n] = 0.0;
                     // PASS 5
                     // rotate
                     double g = 0.0;
                     for(int j = 0; j < p; j ++) {
                         g = a[j + p * n];
                         h = a[j + q * n];
                         a[j + p * n] = g - s * (h + g * tau);
                         a[j + q * n] = h + s * (g - h * tau);
                     }
                     for(int j = p + 1; j < q; j ++) {
                         g = a[p + j * n];
                         h = a[j + q * n];
                         a[p + j * n] = g - s * (h + g * tau);
                         a[j + q * n] = h + s * (g - h * tau);
                     }
                     for(int j = q + 1; j < n; j ++) {
                         g = a[p + j * n];
                         h = a[q + j * n];
                         a[p + j * n] = g - s * (h + g * tau);
                         a[q + j * n] = h + s * (g - h * tau);
                     }
                     // PASS 6
                     // store to eigenvector matrix v
                     for(int j = 0; j < n; j ++) {
                         g = v[j + p * n];
                         h = v[j + q * n];
                         v[j + p * n] = g - s * (h + g * tau);
                         v[j + q * n] = h + s * (g - h * tau);
                     }
                     *rot_num += 1;
                 }
             }
         }
         for(int i = 0; i < n; i ++) {
             bw[i] += zw[i];
             d[i] = bw[i];
             zw[i] = 0.0;
         }
     }
     // PASS 7
     // restore upper triangle
     for(int i = 0; i < n; i ++) {
         for(int j = 0; j < i; j ++) {
             a[j + i * n] = a [i + j * n];
         }
     }
     for(int k = 0; k < n - 1; k ++) {
         int m = k;
         for(int l = k + 1; l < n; l ++) {
             if(d[l] < d[m]) {
                 m = l;
             }
         }
         if(m != k) {
             double t = d[m];
             d[m] = d[k];
             d[k] = t;
             for(int i = 0; i < n; i ++) {
                 double w = v[i + m * n];
                 v[i + m * n] = v[i + k * n];
                 v[i + k * n] = w;
             }
         }
     }
     free(bw);
     free(zw);
     return;
 }
double frobenius_norm (int n, int k, double a[], double x[], double lambda[])
computes the Frobenius norm in a right eigensystem
Parameters
n the dimension of the matrix
k the number of eigen vectors
a[] input matrix of size n by n
x[] input vector of eigenvectors of size k
lamdba[] input vector of eigen values
Returns
double the frobenius norm of A * X - X * lambda
{
     double* c = (double*) malloc(n * k * sizeof(double));
     for(int i = 0; i < k; i ++) {
         for(int j = 0; j < n; j ++) {
             c[j + i * n] = 0.0;
             for(int l = 0; l < n; l ++) {
                 c[j + i * n] = c[j + i * n] + a[j + l * n] * x[l + i * n];
             }
         }
     }
     for(int i = 0; i < k; i ++) {
         for(int j = 0; j < n; j ++) {
             c[j + i * n] = c[j + i * n] - lambda[i] * x[j + i * n];
         }
     }
     // n k c
     // m n a
     double retval = 0.0;
     for(int i = 0; i < k; i ++) {
         for(int j = 0; j < n; j ++) {
             retval += pow(c[j + i * n], 2);
         }
     }
     retval = sqrt(retval);
     free(c);
     return retval;
 }
void mat_identity (int n, double a[])
returns an identity matrix of size n
Parameters
n the dimension
a[] output identity matrix
Referenced by eigen().
{
     int k = 0;
     for (int j = 0; j < n; j ++ ) {
         for (int i = 0; i < n; i ++ ) {
             if ( i == j ) {
                 a[k] = 1.0;
             } else {
                 a[k] = 0.0;
             }
             k += 1;
         }
     }
     return;
 }
void mat_print (const matrix * mat)
prints the matrix this function will not modify the matrix and print to stdout
Parameters
mat the matrix to be printed
{
     for(size_t i = 0; i < mat->row; i ++) {
         for(size_t j = 0; j < mat->col; j ++) {
             printf("%f, ", MAT(mat, i, j));
         }
         printf("\n");
     }
 }
matrix* mat_transpose (const matrix * mat)
Performs transpose(mat) this function will malloc for the user a matrix*.
Returns
a matrix*
Parameters
matA
Referenced by covmat().
 {
     matrix *retVal = matrix_create(mat->col, mat->row);
     for (size_t i = 0; i < mat->row; i++)
     {
         for (size_t j = 0; j < mat->col; j++)
         {
             MAT(retVal,j,i) = MAT(mat,i,j);
         }
     }
     return retVal;
 }
matrix* matmat_addition (const matrix * matA, const matrix * matB)
Performs matrixA + matrixB this function will malloc for the user a matrix*.
Returns
a matrix*
Parameters
matA
matB
 {
     matrix *retVal = matrix_create(matA->row, matB->col);
     for (size_t i = 0; i < matA->row; i++)
     {
         for (size_t j = 0; j < matB->col; j++)
         {
             MAT(retVal,i,j) = MAT(matA,i,j) + MAT(matB,i,j);
         }
     }
     return retVal;
 }
matrix* matmat_multiply (const matrix * matA, const matrix * matB)
Performs matrixA * matrixB this function will malloc for the user a matrix*.
Returns
a matrix*
Parameters
matA
matB
Referenced by covmat().
 {
     matrix *retVal = matrix_create(matA->row, matB->col);
     for(size_t i =0; i<matA->row;i++)
     {
         for(size_t j=0; j<matB->col;j++)
         {
             MAT(retVal,i,j) = 0;
             for(size_t k=0; k<matA->col;k++)
             {
                 MAT(retVal,i,j) += MAT(matA,i,k)*MAT(matB,k,j);
             }
         }
     }
     return retVal;
 }
matrix* matmat_subtraction (const matrix * matA, const matrix * matB)
Performs matrixA - matrixB this function will malloc for the user a matrix*.
Returns
a matrix*
Parameters
matA
matB
 {
     matrix *retVal = matrix_create(matA->row, matB->col);
     for (size_t i = 0; i < matA->row; i++)
     {
         for (size_t j = 0; j < matB->col; j++)
         {
             MAT(retVal,i,j) = MAT(matA,i,j) - MAT(matB,i,j);
         }
     }
     return retVal;
 }
void matrix_reshape (matrix * mat, size_t row, size_t col)
Reshapes the matrix this function will reshape the matrix in constant time.
Parameters
matrix* to be reshaped
size_t row for the new row
size_t col for the new column
{
     mat->row = row;
     mat->col = col;
 }
matrix* matscalar_divide (const matrix * matA, const double scalar)
Performs matrixA / scaler this function will malloc for the user a matrix*.
Returns
a matrix*
Parameters
matA
scalar
Referenced by covmat().
 {
     matrix *retVal = matrix_create(matA->row, matA->col);
     for (size_t i = 0; i < matA->row; i++)
     {
         for (size_t j = 0; j < matA->col; j++)
         {
             MAT(retVal,i,j) = MAT(matA,i,j) /scalar;
         }
     }
     return retVal;
 }
matrix* matscalar_multiply (const matrix * matA, const double scalar)
Performs matrixA * scaler this function will malloc for the user a matrix*.
Returns
a matrix*
Parameters
matA
scalar
 {
     matrix *retVal = matrix_create(matA->row, matA->col);
     for (size_t i = 0; i < matA->row; i++)
     {
         for (size_t j = 0; j < matA->col; j++)
         {
             MAT(retVal,i,j) = MAT(matA,i,j) *scalar;
         }
     }
     return retVal;
 }
vector* matvec_multiply (const matrix * mat, const vector * vec)
Performs matrix * vector this function will malloc for the user a vector*.
Returns
a vector*
Parameters
mat
vec
References dot_product().
 {
     if(vec == NULL  || mat == NULL) {
         return NULL;
     }
     vector *retVec = vector_create(vec->size);
     for(size_t i =0; i< retVec->size; i++)
     {
         VEC(retVec,i) = dot_product(((double*)(mat->data) + (mat->col * i)), (double*)vec->data, vec->size);
     }
     return retVec;
 }
void vec_append (vector ** vec_a, vector * vec_b)
Performs vec = vec_a+vec_b this function will realloc vec_a and free vec_b.
Performs vecA = vecA+vecB this function will realloc for the user vectorA and destroys vecB.
Returns
void
Parameters
vec_a
vec_b
 {
     void* saved_vec_a = *vec_a;
     vector* buffer = vector_create(vec_b->size);
     memcpy(buffer, vec_b, sizeof(double) * vec_b->size + (2 * sizeof(size_t)));
     size_t newSize = (*vec_a)->size + buffer->size;
     void* dest = *vec_a;
     void* arrv = NULL;
     arrv = realloc(dest, sizeof(double) * newSize + (2 * sizeof(size_t)));
     *vec_a = arrv;
     memcpy((*vec_a)->data + (*vec_a)->size, buffer->data, buffer->size *sizeof(double));
     (*vec_a)->size = newSize;
     free(buffer);
     if(saved_vec_a != vec_b)
     {
         free(vec_b);
     }
 }
void vec_print (const vector * vec)
prints the vector this function will not modify the vector and print to stdout
Parameters
vec the vector to be printed
{
     for(size_t i = 0; i < vec->size; i ++) {
         // printf("%f, ", VEC(vec, i));
         printf("%f ", vec->data[i]);
     }
     printf("\n");
 }
matrix* vec_to_mat (vector * vec, int orientation)
Converts vector into matrix this function will "cast" the vector into a matrix by using the fact that they both have the same size. when calling this function, calling free() on the matrix will free the vector and vice versa.
Returns
a matrix*
Parameters
vector* to be converted
int orientation where 1 is Row-wise and 0 is Column-wise
{
     if(orientation == 1) {
         vec->padding = vec->size;
         vec->size = 1;
     } else {
         vec->padding = 1;
     }
     return (matrix*)vec;
 }
vector* vecmat_multiply (const vector * vec, const matrix * mat)
Performs vector * matrix this function will malloc for the user a vector*.
Returns
a vector*
Parameters
vec
mat
{
     if(vec == NULL  || mat == NULL) {
         return NULL;
     }
     vector* retvec = vector_create(vec->size);
     memset(retvec->data, 0, sizeof(double) * vec->size);
     for(size_t j = 0; j < mat->col; j ++) {
         for(size_t i = 0; i < mat->row; i ++) {
             VEC(retvec, j) += (VEC(vec, i) * MAT(mat, i, j));
         }
     }
     return retvec;
 }